"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const CreateCursoController_1 = require("./controllers/CreateCursoController");
const ListCursosController_1 = require("./controllers/ListCursosController");
const UpdateCursoController_1 = require("./controllers/UpdateCursoController");
const SingleCursoController_1 = require("./controllers/SingleCursoController");
const DeleteCursoController_1 = require("./controllers/DeleteCursoController");
const router = (0, express_1.Router)();
exports.router = router;
router.get('/cursos', new ListCursosController_1.ListCursosController().handle);
router.get('/curso/:id', new SingleCursoController_1.SingleCursoController().handle);
router.post('/curso', new CreateCursoController_1.CreateCursoController().handle);
router.put('/curso/update/:id', new UpdateCursoController_1.UpdateCursoController().update);
router.delete('/curso/delete/:id', new DeleteCursoController_1.DeleteIdController().handle);
